from enum import Enum


class LoopState(str, Enum):
    LOAD_PROJECT = "LOAD_PROJECT"
    ASSEMBLE_CONTEXT = "ASSEMBLE_CONTEXT"
    WRITE_DRAFT = "WRITE_DRAFT"
    REVISE_DRAFT = "REVISE_DRAFT"
    CHECK_CONTINUITY = "CHECK_CONTINUITY"
    BUILD_REVISION_PLAN = "BUILD_REVISION_PLAN"
    WAIT_HUMAN_APPROVAL = "WAIT_HUMAN_APPROVAL"
    AUTO_COMMITTING = "AUTO_COMMITTING"
    COMMITTED = "COMMITTED"
    UPDATING_STORY_MEMORY = "UPDATING_STORY_MEMORY"
    MEMORY_UPDATED = "MEMORY_UPDATED"
    PAUSED = "PAUSED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    STOPPED = "STOPPED"
    FAILED = "FAILED"


TRANSITIONS = {
    LoopState.LOAD_PROJECT: LoopState.ASSEMBLE_CONTEXT,
    LoopState.ASSEMBLE_CONTEXT: LoopState.WRITE_DRAFT,
    LoopState.WRITE_DRAFT: LoopState.CHECK_CONTINUITY,
    LoopState.REVISE_DRAFT: LoopState.CHECK_CONTINUITY,
    LoopState.CHECK_CONTINUITY: LoopState.WAIT_HUMAN_APPROVAL,
    LoopState.BUILD_REVISION_PLAN: LoopState.REVISE_DRAFT,
    LoopState.AUTO_COMMITTING: LoopState.COMMITTED,
    LoopState.COMMITTED: LoopState.UPDATING_STORY_MEMORY,
    LoopState.UPDATING_STORY_MEMORY: LoopState.MEMORY_UPDATED,
}


TERMINAL_STATES = {
    LoopState.WAIT_HUMAN_APPROVAL,
    LoopState.APPROVED,
    LoopState.REJECTED,
    LoopState.FAILED,
    LoopState.PAUSED,
    LoopState.MEMORY_UPDATED,
    LoopState.STOPPED,
}
