"""pre mvp 1.1 schema baseline

Revision ID: 8cd023ae54b4
Revises:
Create Date: 2026-06-12 10:47:29.909974
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '8cd023ae54b4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_providers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('provider_type', sa.String(length=64), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('model', sa.String(length=240), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('default_options_json', sa.Text(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_test_status', sa.String(length=32), nullable=False),
    sa.Column('last_test_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('template_text', sa.Text(), nullable=False),
    sa.Column('output_schema_json', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_templates_key'), ['key'], unique=True)

    op.create_table('novels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('synopsis', sa.Text(), nullable=False),
    sa.Column('story_outline', sa.Text(), nullable=False),
    sa.Column('style_guide', sa.Text(), nullable=False),
    sa.Column('forbidden_content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('novels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_novels_project_id'), ['project_id'], unique=False)

    op.create_table('canon_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('novel_id', sa.String(length=36), nullable=False),
    sa.Column('character_states_json', sa.Text(), nullable=False),
    sa.Column('relationships_json', sa.Text(), nullable=False),
    sa.Column('unresolved_conflicts_json', sa.Text(), nullable=False),
    sa.Column('active_foreshadowing_json', sa.Text(), nullable=False),
    sa.Column('key_events_json', sa.Text(), nullable=False),
    sa.Column('chapter_summaries_json', sa.Text(), nullable=False),
    sa.Column('progress_notes', sa.Text(), nullable=False),
    sa.Column('pending_character_updates_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('canon_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_canon_states_novel_id'), ['novel_id'], unique=True)

    op.create_table('chapters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('novel_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id', 'order_index', name='uq_chapter_order')
    )
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapters_novel_id'), ['novel_id'], unique=False)

    op.create_table('characters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('novel_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('personality', sa.Text(), nullable=False),
    sa.Column('goals', sa.Text(), nullable=False),
    sa.Column('arc', sa.Text(), nullable=False),
    sa.Column('current_state_json', sa.Text(), nullable=False),
    sa.Column('relationships_json', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_characters_novel_id'), ['novel_id'], unique=False)

    op.create_table('creative_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('novel_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=True),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('idea', sa.Text(), nullable=False),
    sa.Column('reference_text', sa.Text(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('options_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['model_providers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('creative_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creative_runs_novel_id'), ['novel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_runs_provider_id'), ['provider_id'], unique=False)

    op.create_table('locations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('novel_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('current_state_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_novel_id'), ['novel_id'], unique=False)

    op.create_table('plot_threads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('novel_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=False),
    sa.Column('related_chapter_ids_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plot_threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plot_threads_novel_id'), ['novel_id'], unique=False)

    op.create_table('world_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('novel_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('world_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_world_rules_novel_id'), ['novel_id'], unique=False)

    op.create_table('chapter_loop_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('novel_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('context_budget', sa.Integer(), nullable=False),
    sa.Column('options_json', sa.Text(), nullable=False),
    sa.Column('assembled_context', sa.Text(), nullable=False),
    sa.Column('continuity_report_json', sa.Text(), nullable=False),
    sa.Column('current_version_id', sa.String(length=36), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['model_providers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapter_loop_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapter_loop_runs_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter_loop_runs_novel_id'), ['novel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter_loop_runs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter_loop_runs_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter_loop_runs_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter_loop_runs_status'), ['status'], unique=False)

    op.create_table('chapter_outlines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('outline_content', sa.Text(), nullable=False),
    sa.Column('required_plot_points_json', sa.Text(), nullable=False),
    sa.Column('character_ids_json', sa.Text(), nullable=False),
    sa.Column('location_ids_json', sa.Text(), nullable=False),
    sa.Column('style_notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapter_outlines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapter_outlines_chapter_id'), ['chapter_id'], unique=True)

    op.create_table('foreshadowing',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('novel_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('planted_chapter_id', sa.String(length=36), nullable=True),
    sa.Column('resolved_chapter_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['planted_chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('foreshadowing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_foreshadowing_novel_id'), ['novel_id'], unique=False)

    op.create_table('timeline_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('novel_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('story_time', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('character_ids_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timeline_events_novel_id'), ['novel_id'], unique=False)

    op.create_table('writing_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=True),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('options_json', sa.Text(), nullable=False),
    sa.Column('pause_requested', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['model_providers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('writing_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_writing_tasks_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_writing_tasks_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_writing_tasks_status'), ['status'], unique=False)

    op.create_table('chapter_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('parent_version_id', sa.String(length=36), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_version_id'], ['chapter_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['chapter_loop_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id', 'version_number', name='uq_chapter_version_number')
    )
    with op.batch_alter_table('chapter_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapter_versions_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter_versions_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter_versions_run_id'), ['run_id'], unique=False)

    op.create_table('generation_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=True),
    sa.Column('prompt_template_key', sa.String(length=120), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('options_json', sa.Text(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['model_providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['writing_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_runs_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_runs_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_runs_task_id'), ['task_id'], unique=False)

    op.create_table('run_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('input_json', sa.Text(), nullable=False),
    sa.Column('output_json', sa.Text(), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['chapter_loop_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'sequence', name='uq_run_step_sequence')
    )
    with op.batch_alter_table('run_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_steps_run_id'), ['run_id'], unique=False)

    op.create_table('scene_outlines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chapter_outline_id', sa.String(length=36), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('outline_content', sa.Text(), nullable=False),
    sa.Column('character_ids_json', sa.Text(), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_outline_id'], ['chapter_outlines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scene_outlines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scene_outlines_chapter_outline_id'), ['chapter_outline_id'], unique=False)

    op.create_table('model_calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('step_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=True),
    sa.Column('agent_name', sa.String(length=120), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('raw_response_json', sa.Text(), nullable=False),
    sa.Column('parsed_json', sa.Text(), nullable=False),
    sa.Column('options_json', sa.Text(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['model_providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['chapter_loop_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['run_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_calls_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_calls_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_calls_step_id'), ['step_id'], unique=False)

    op.create_table('review_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('generation_run_id', sa.String(length=36), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('goal_alignment', sa.Text(), nullable=False),
    sa.Column('character_consistency', sa.Text(), nullable=False),
    sa.Column('timeline_consistency', sa.Text(), nullable=False),
    sa.Column('repetition', sa.Text(), nullable=False),
    sa.Column('missing_plot_points', sa.Text(), nullable=False),
    sa.Column('style_issues', sa.Text(), nullable=False),
    sa.Column('suggestions_json', sa.Text(), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generation_run_id'], ['generation_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_results_chapter_id'), ['chapter_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_results_chapter_id'))

    op.drop_table('review_results')
    with op.batch_alter_table('model_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_calls_step_id'))
        batch_op.drop_index(batch_op.f('ix_model_calls_run_id'))
        batch_op.drop_index(batch_op.f('ix_model_calls_provider_id'))

    op.drop_table('model_calls')
    with op.batch_alter_table('scene_outlines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scene_outlines_chapter_outline_id'))

    op.drop_table('scene_outlines')
    with op.batch_alter_table('run_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_steps_run_id'))

    op.drop_table('run_steps')
    with op.batch_alter_table('generation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generation_runs_task_id'))
        batch_op.drop_index(batch_op.f('ix_generation_runs_provider_id'))
        batch_op.drop_index(batch_op.f('ix_generation_runs_chapter_id'))

    op.drop_table('generation_runs')
    with op.batch_alter_table('chapter_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter_versions_run_id'))
        batch_op.drop_index(batch_op.f('ix_chapter_versions_content_hash'))
        batch_op.drop_index(batch_op.f('ix_chapter_versions_chapter_id'))

    op.drop_table('chapter_versions')
    with op.batch_alter_table('writing_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_writing_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_writing_tasks_provider_id'))
        batch_op.drop_index(batch_op.f('ix_writing_tasks_chapter_id'))

    op.drop_table('writing_tasks')
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timeline_events_novel_id'))

    op.drop_table('timeline_events')
    with op.batch_alter_table('foreshadowing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_foreshadowing_novel_id'))

    op.drop_table('foreshadowing')
    with op.batch_alter_table('chapter_outlines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter_outlines_chapter_id'))

    op.drop_table('chapter_outlines')
    with op.batch_alter_table('chapter_loop_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter_loop_runs_status'))
        batch_op.drop_index(batch_op.f('ix_chapter_loop_runs_state'))
        batch_op.drop_index(batch_op.f('ix_chapter_loop_runs_provider_id'))
        batch_op.drop_index(batch_op.f('ix_chapter_loop_runs_project_id'))
        batch_op.drop_index(batch_op.f('ix_chapter_loop_runs_novel_id'))
        batch_op.drop_index(batch_op.f('ix_chapter_loop_runs_chapter_id'))

    op.drop_table('chapter_loop_runs')
    with op.batch_alter_table('world_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_world_rules_novel_id'))

    op.drop_table('world_rules')
    with op.batch_alter_table('plot_threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plot_threads_novel_id'))

    op.drop_table('plot_threads')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_novel_id'))

    op.drop_table('locations')
    with op.batch_alter_table('creative_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_runs_provider_id'))
        batch_op.drop_index(batch_op.f('ix_creative_runs_novel_id'))

    op.drop_table('creative_runs')
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_characters_novel_id'))

    op.drop_table('characters')
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapters_novel_id'))

    op.drop_table('chapters')
    with op.batch_alter_table('canon_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_canon_states_novel_id'))

    op.drop_table('canon_states')
    with op.batch_alter_table('novels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_novels_project_id'))

    op.drop_table('novels')
    with op.batch_alter_table('prompt_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_templates_key'))

    op.drop_table('prompt_templates')
    op.drop_table('projects')
    op.drop_table('model_providers')
    # ### end Alembic commands ###
